services:
  app:
    build:
      context: ./backend # IMPORTANTE: Indica que el Dockerfile está dentro de la carpeta backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www/html # Sincroniza tu carpeta local con el contenedor
      - /var/www/html/vendor # Evita que los archivos locales sobrescriban las dependencias del contenedor
    ports:
      - "${PORT_BACKEND}:8000"
    depends_on:
      - db
    env_file:
      - ./backend/.env # Usa el archivo .env que está dentro de backend

  # La base de datos (PostgreSQL)
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DOCKER_DB_NAME}
      POSTGRES_USER: ${DOCKER_DB_USER}
      POSTGRES_PASSWORD: ${DOCKER_DB_PASSWORD}
    ports:
      - "${PORT_POSTGRES}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules # Evita que los archivos locales sobrescriban las librerías del contenedor
    ports:
      - "${PORT_FRONTEND}:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:${PORT_BACKEND}/api # URL para que el navegador encuentre el backend
    depends_on:
      - app
    
  # Módulo de Inteligencia Artificial
  ia:
    build:
      context: ./ia
      dockerfile: Dockerfile
    volumes:
      - ./ia:/app
      - /app/node_modules # Evita que los archivos locales sobrescriban las librerías del contenedor
    ports:
      # Asigna un puerto diferente (3001) en tu máquina para no chocar con el frontend
      - "${PORT_IA:-3001}:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_API_URL=http://app:8000
    env_file:
      - ./ia/.env # Usa el archivo .env configurado para la IA
    depends_on:
      - app

volumes:
  postgres_data:


