services:
  # El servidor de Laravel (PHP)
  app:
    build:
      context: .
      dockerfile: Dockerfile # Asegúrate de tener un Dockerfile en la carpeta
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - db

  # La base de datos (PostgreSQL)
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: gima_bd
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: jF2811
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
